### ISSUE TITLE
How to Connect Securely with Datastream

### ISSUE THREAD

**Issue by DBoudart23** [GoogleCloudPlatform/alloydb-auth-proxy#682]
### Description

I've followed this [GCP page](https://cloud.google.com/datastream/docs/configure-alloydb-psql) to configure Datastreams, but it seems outdated.

Can you kindly have a look?

**Comment by enocom** [comment]
Thanks -- we missed that in the latest release process.

**Comment by enocom** [comment]
Actually that page shows you how to use gcr.io/dms-images/tcp-proxy which is a simple TCP proxy. You'll see the install page does reference the latest version.

https://cloud.google.com/alloydb/docs/auth-proxy/connect#install

**Comment by DBoudart23** [comment]
Yea, we are looking for the simple option, can we use the same commands but pointing to the latest version?

**Comment by enocom** [comment]
To take a step back, would you mind framing this with a problem statement? I can advise accordingly.

**Comment by DBoudart23** [comment]
We are trying to connect Datastreams hosted in project-A within a VPC named Network-1 to AlloyDB hosted in a separate project-B within a VPC named Network-2. We followed all the steps shared in the documentation but when pulling this container image `gcr.io/dms-images/tcp-proxy` and opening the link it redirects me to an decommissioned GCP feature (Container registry - see image attached) which I'm afraid to implement what is suggested in the documentation and anytime soon it will disappear.
![image](https://github.com/user-attachments/assets/ce18a213-bd28-450f-9227-ec563523d92f)

Hence, I'm trying to use the latest version you have within the Artifact registry that replaced the decommissioned Container Registry. I would appreciate any help on using your latest version and what should be adapted in this command 👇 

```
gcloud compute instances create-with-container \
  --zone=us-central1-c ds-tcp-proxy \
  --container-image gcr.io/dms-images/tcp-proxy \
  --tags=ds-tcp-proxy \
  --container-env=SOURCE_CONFIG=[IP_ADDRESS]:[PORT] \
  --can-ip-forward \
  --network=default \
  --machine-type=e2-micro
  --metadata=startup-script='#! /bin/bash
  mkdir -p /etc/docker
  cat <<EOF > /etc/docker/daemon.json
  {"bridge":"none"}
  EOF
  systemctl restart docker'
```

**Comment by enocom** [comment]
I reached out to the team that maintains the tcp-proxy and they assured me they'll be migrating the image to Artifact Registry before the cutoff.

So you're fine to keep using tcp-proxy.

Using the Auth Proxy itself would work, but would also be inherently insecure because the Auth Proxy assumes it runs on the same machine as the workload -- if it's used as a more typical proxy sitting in between two machines on a third machine, anyone who has access to that middle machine would also have access to your database without any kind of auth, encryption, etc. So TL:DR tcp-proxy is the way to go.

Have you explored using PSC for your AlloyDB instance? That would at least remove the need for the tcp-proxy and you could connect Dreamstream directly to a PSC endpoint in "Network 1".

**Comment by DBoudart23** [comment]
@enocom, much obliged for this info and also for checking with the team that they will migrate.

I'll be honest, and I'm not aware of what PSC is, but I would be glad to reduce complexity and enable direct connection of Datastream in "Network2" to AlloyDB in "Network1". Do you mind guiding me on that one? I fully understand if this takes more time from you.

**Comment by enocom** [comment]
Big picture the problem you're hitting is that transitively peered VPCs don't provide a network path. See https://cloud.google.com/vpc/docs/vpc-peering#transit-network for a detailed explanation. In short, your network path looks like this:

Datastream-managed VPC <--(peering)--> Network-1 <--(peering)--> Network-2 <--(peering)--> AlloyDB-managed VPC

[Private Service Connect](https://cloud.google.com/alloydb/docs/about-private-service-connect) is meant to solve this problem. Instead of using VPC peering, you would create an endpoint in Network-1 that is attached to your AlloyDB instance. This way Datastream can just connect to the endpoint in Network-1 and you can skip the trouble of running the tcp-proxy. The downside is if you're fully invested in a hub-and-spoke VPC network design, you're sacrificing some of the purity of the hub by having AlloyDB reachable from Network-1 (as opposed to Network-2).

**Comment by DBoudart23** [comment]
Thank you very much @enocom , super helpful. Life saver :)

**Comment by enocom** [comment]
Glad that helps. I'll close this in the meantime.
